package com.group1.swp.pizzario_swp391.mapper;

import com.group1.swp.pizzario_swp391.dto.product.ProductWebSocketDTO;
import com.group1.swp.pizzario_swp391.entity.Product;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.NullValuePropertyMappingStrategy;

/**
 * MapStruct mapper interface for Product to ProductWebSocketDTO conversion
 * Implementation will be automatically generated by MapStruct
 */
@Mapper(componentModel = "spring", nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
public interface ProductWebSocketMapper {

    /**
     * Convert Product entity to ProductWebSocketDTO
     * 
     * @param product Product entity
     * @return ProductWebSocketDTO or null if product is null
     */
    @Mapping(source = "category.id", target = "categoryId")
    @Mapping(source = "category.name", target = "categoryName")
    ProductWebSocketDTO toWebSocketDTO(Product product);
}